name: tagz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  android_id: ^0.3.3
  archive: ^3.3.7
  device_info_plus: ^9.0.2
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_downloader: ^1.10.5
  http: ^1.1.0
  multi_select_flutter: ^4.1.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
